### ISSUE TITLE
Help maintaining repo

### ISSUE THREAD

**Issue by nathanchapman** [JoelBesada/activate-power-mode#123]
@JoelBesada I've noticed no new commits or merged pull requests in ~4 months. If you need help maintaining this repo, I will gladly help test & merge PRs if you add me as a contributor.

This is an awesome plugin and I'd love to see it progress. I think the rest of the community would as well.

**Comment by JoelBesada** [comment]
@nathanchapman Hi, thank you for offering to do this! I've added you as a contributor to the repository now. 

The main reason I haven't been actively working on this is because I haven't yet been able to transition to using Atom as my every day editor. This makes it harder to find the motivation to continue on it, since the plugin isn't something I'm able to use myself. 

If anyone else is reading this and would also like to help out as a contributor, please let me know.

**Comment by nathanchapman** [comment]
@JoelBesada Thanks Joel! I'm in midterms right now. I'll get started with some testing & merging in the next week or two

**Comment by lexcast** [comment]
Hi! I would like to help too.
@nathanchapman do you have any plan regarding to the merging and testing in mind?

**Comment by nathanchapman** [comment]
@lexcast A lot of the bugs are with newer versions of Atom and have to do with particles rending in the wrong spots or not in multiple panes. I have to finish up this last stretch of midterms and then I'll start on testing and merging. I'm sure @JoelBesada wouldn't mind adding you as a contributor. There's a considerable amount of work that needs to go into the current pull requests (plugin system, etc.) and fixing the rendering bugs. We just need to keep track of who's working on which PRs and issues with the github assignee feature

**Comment by JoelBesada** [comment]
I definitely appreciate the help! I've added you as a contributor too @lexcast.

**Comment by lexcast** [comment]
Thanks a lot.
When I was working on my PR I found some calls to deprecated methods, I will see if the rendering on wrong positions is because of that.
