### ISSUE TITLE
I wish it could use in sublime oneday

### ISSUE THREAD

**Issue by ChuckIsReady** [JoelBesada/activate-power-mode#14]
:-)

**Comment by chinchang** [comment]
This might not be straightforward for Sublime as its not a web app.

**Comment by a1c2n3g4w5** [comment]
+1

**Comment by roth1002** [comment]
+100

**Comment by CN-Sean** [comment]
in webstorm +1

**Comment by ChuckIsReady** [comment]
yes，after that i searched it and found sublime is a python app and atom is a web app .

**Comment by flydsc** [comment]
sublime +1

**Comment by geeyan** [comment]
+1

**Comment by fever324** [comment]
+1

**Comment by abrkn** [comment]
:+1:

**Comment by alexgleason** [comment]
Instead of asking for Sublime support, switch to Atom. It's a better editor and it's free.

There's no reason to continue supporting proprietary software when a community alternative exists. This plugin exists for Atom and not Sublime for a reason.

**Comment by halfnibble** [comment]
@alexgleason I use both regularly. I understand why this plugin may not be feasible on SublimeText (proprietary, native code and all). But I also understand why others want it. Atom just doesn't run as well as SublimeText does on systems with limited resources.

But, everyone should just go out and buy a Macbook Pro anyway. ;-)

**Comment by igetsman** [comment]
Cooooooool! looking forward on siblime 2/3 too

**Comment by abrkn** [comment]
> Instead of asking for Sublime support, switch to Atom. It's a better editor and it's free.
Followed your advice and am very happy to have switched.

**Comment by murilobast** [comment]
The only thing that's holding me is the sublime's visual indentation indicator. I can't live without that feature, apart from that, Atom is a better text editor.

**Comment by alexgleason** [comment]
What? You mean the ability to see whitespace? That's built into Atom.

**Comment by murilobast** [comment]
@alexgleason I mean the dashes and dots (dashes for tabs and dots to indicate spaces).

**Comment by alexgleason** [comment]
Atom has this built into the settings by default. Just tick the box that
says "visible whitespace" or something to that extent.

**Comment by murilobast** [comment]
@alexgleason lol, thanks man. Worked pretty well hahahah

**Comment by luthorlex** [comment]
+1

**Comment by J2TeaM** [comment]
:+1:

**Comment by TrangDinhVan** [comment]
It would save my life, I died.

**Comment by ekaekaeka** [comment]
+1

**Comment by Nigorro** [comment]
+АДЫН!

**Comment by WarHawk1** [comment]
Sublime can run with quite limited resources as compared to atom.

**Comment by elfenars** [comment]
+1

**Comment by amitpatil321** [comment]
If you see the benchmarks, You will come to know that sublime is much much faster than atop.

**Comment by maketroli** [comment]
SUBLIME TEXT IS THE FATHER! Atom is fucking slow, it closes sometimes when is unable to run some stuff. The UX is still shitty. Sublime combined with [https://github.com/equinusocio/material-theme](this theme) and some of the suggestions at the end of the README.md is the best thing. I used Atom for 2 months, and I just get back to Sublime.

**Comment by cinder92** [comment]
+1

**Comment by Luavis** [comment]
+1

**Comment by mashtullah** [comment]
@alexgleason I don't understand why you insist we switch to Atom instead of just making this plugin for sublime?? I use both but for different reasons, small scripts, sketches, code golf and such off work stuff i use Atom, but when i want to work on my projects and any other real work i use Sublime.
Its all about the performance...

**Comment by alexgleason** [comment]
Firstly, Sublime is built using a native UI toolkit, so making particles appear when you type is not trivial. For Atom it's very simple, because you can just throw an HTML5 canvas directly into the app.

Also, Atom is better for a number of reasons:

1. Free and open source
2. Supports plugins by default
3. Git integration by default
4. Modular and built to be modified
5. Easier to develop for
6. Built with web languages

Downsides:

1. It's slower. Don't open minified files.

If you have a decent computer, use Atom. If you don't, you're not going to get to have colored particles emit from your cursor when you type.

**Comment by elfenars** [comment]
Why instead of trying to change everyone's mind don't we just agree this is one of the oldest discussions in the modern IT world and just move along into making this happen?

Vim vs Emacs
Text editors vs IDEs
Sublime vs Atom

Honestly, nobody could give two craps about what you use and why you use it... this is just about asking to integrate a cool new feature (which is not even important for REAL development) and trying to convince the core dev into making it.

THAT'S.ALL.THERE.IS.TO.IT

**Comment by alexgleason** [comment]
If you want it, go ahead and make it. But there is no way the devs of this project are going to attempt to port this functionality to an editor that rigid. You may as well ask for this to be ported to Vim.

**Comment by elfenars** [comment]
Well, let them decide... if you're not going to contribute then why bother even being here.

**Comment by alexgleason** [comment]
You don't understand how open source software works. If you want it, build it. The developers behind this aren't getting paid money to produce these things. It was done for free, out of personal interest. From what I can tell, there is no incentive for them to attempt to rebuild this functionality in anything but a web-based user interface. Even implementing this in Atom was nontrivial. In Sublime, I question whether it's even possible.

My contribution is informing you all that this suggestion is nontrivial, and that Atom is worth switching to if you aren't aware.

**Comment by elfenars** [comment]
Yes, you're entirely right... the open source world works exactly like that and everything that has been said here is entirely wrong. We should all move to Atom and stop this nonsense, why would we even ask for it, what were we thinking.

Thank GOD we have people like you here to makes us understand how little important our opinions and interests as developers are.

**Comment by lexcast** [comment]
This is not an issue with the package.
If you want this feature for another editor check out [codeinthedark/awesome-power-mode](https://github.com/codeinthedark/awesome-power-mode).

AFAIK there is not a port for sublime yet.

**Comment by lexcast** [comment]
codeinthedark/awesome-power-mode#3

**Comment by wemersonblend** [comment]
+1

**Comment by maketroli** [comment]
If you are a pussy then go ahead and use Atom, otherwise stick with Sublime, which is the best text editor and you can make it looks awesome. Let's be honest: Atom isn't a high performance text editor.

<img width="1277" alt="screen shot 2016-08-09 at 2 51 38 pm" src="https://cloud.githubusercontent.com/assets/8395866/17533093/911c3bb8-5e40-11e6-8410-74294c2c6bb2.png">

**Comment by halfnibble** [comment]
@maketroli It looks like you still need to register your copy of Sublime Text...

**Comment by metorm** [comment]
+ 65535

**Comment by snapsurf** [comment]
@maketroli What theme are you using in that last screenshot?

**Comment by erasmo-marin** [comment]
@snapsurf It's material theme

@halfnibble I have a macbook pro, but even on mac, I prefer Sublime, it's a lot faster, I don't understand why to make a web text editor, it's a bad idea, the same for terminal emulators like hyper, they are slow as hell

**Comment by halfnibble** [comment]
@erasmo-marin Yeah, I actually had to switch back to SublimeText a few months ago. I was working on a large project with thousands of files, and Atom just choked on it. Even with my state-of-the-art MacBook Pro.

But I still keep Atom installed with "activate-power-mode" just in case I need to audition for a Hollywood hacker role.

**Comment by erasmo-marin** [comment]
@halfnibble lol that's true, at the end, atom is just a toy, and that is sad because I like to support open source projects, and I think that the community is able to build a good text editor. Right now I'm working on a very big project too, and it would be annoying to do it on Atom.

**Comment by ancm-s** [comment]
+1

**Comment by maketroli** [comment]
You should use Atom for some time in order to understand how better is Sublime Text. Every person I know has used Atom and some months after they get back to Sublime for obvious reasons. A simple plugin doesn't make a text editor better than the other. And actually: use that plugin for a week without removing it, it's just fucking annoying to your eyes.

**Comment by rolzing** [comment]
@maketroli yooo bro, can you tell what plugins do you have ? i like how your sublime looks like

thank you    👍🏻

**Comment by lynn9388** [comment]
@rolzing I think he use the [Material Theme](https://packagecontrol.io/packages/Material%20Theme).

**Comment by DevNIX** [comment]
@lynn9388 @rolzing plus https://github.com/equinusocio/material-theme-appbar :)

**Comment by maketroli** [comment]
Sorry I am TOOOOOO late, so sorry mates. And yes, it is Material Theme :)

**Comment by rolzing** [comment]
@DevNIX thanks broo!

**Comment by songleo** [comment]
+1
